/**
 * Export renderer: (story-filtered, redacted events + analytics) → ONE
 * self-contained HTML file.
 *
 * Properties:
 * - Fully static: no JavaScript, no external resources, no network fetches.
 *   Collapsible sections use native <details>. Charts are inline SVG.
 * - XSS-safe by construction: every dynamic string passes through esc();
 *   a restrictive CSP meta tag (default-src 'none') is belt-and-braces.
 * - Bilingual chrome (zh default / en); message content stays untouched.
 * - Privacy: only whitelisted story events are rendered (see redact.ts), so
 *   the system prompt and other internal plumbing can never appear.
 */

import { analyzeSession, formatDuration, formatTokens, type SessionAnalytics } from "./analytics.ts";
import {
  asRecord,
  assistantContent,
  assistantProvenance,
  textOf,
  toolResultContent,
  toolResultIsError,
  type ContentBlock,
  type SessionEvent,
  type SessionHeader,
} from "./events.ts";
import {
  filterStoryEvents,
  redactEvents,
  type RedactOptions,
} from "./redact.ts";

/**
 * Report theme:
 * - `dark` — always dark gray-black, independent of the viewer's OS (default).
 * - `light` — always light.
 * - `system` — follows the viewer's `prefers-color-scheme`.
 */
export type ExportTheme = "system" | "light" | "dark";

export interface ExportOptions extends RedactOptions {
  lang?: "zh" | "en";
  theme?: ExportTheme;
}

type Lang = "zh" | "en";

const STRINGS = {
  zh: {
    report: "会话洞察报告",
    generatedBy: "由 dsh-session-lens 生成",
    privacyNote: "隐私说明：本文件不含系统提示词与内部请求事件；本地路径已脱敏为 ~；图片不导出。",
    privacyNoteFull: "隐私说明：本文件不含系统提示词与内部请求事件；图片不导出。",
    tokens: "Token 用量",
    input: "输入",
    output: "输出",
    cacheRead: "缓存读",
    cacheWrite: "缓存写",
    reasoning: "思维链",
    compaction: "压缩摘要调用",
    total: "合计",
    perTurn: "按 Turn 分解",
    turn: "Turn",
    duration: "时长",
    toolCalls: "工具调用",
    errors: "错误",
    messages: "消息",
    tools: "工具统计",
    tool: "工具",
    calls: "调用",
    activity: "活动统计",
    compactions: "上下文压缩",
    shadowed: "压缩遮蔽 token",
    approvals: "审批",
    subagents: "子 Agent",
    retries: "LLM 重试",
    replay: "会话回放",
    reasoningToggle: "思维链",
    toolArgs: "参数",
    toolResult: "结果",
    errorBadge: "错误",
    turnDivider: "Turn",
    approvalAsked: "请求审批",
    approvalApproved: "已批准",
    approvalDenied: "已拒绝",
    compactionMarker: "上下文压缩",
    subagentMarker: "子 Agent",
    planMode: "计划模式",
    todoUpdated: "Todo 更新",
    feedback: "反馈",
    user: "用户",
    assistant: "助手",
    model: "模型",
    status: "状态",
    statusActive: "进行中",
    createdAt: "创建时间",
    eventCount: "事件数",
    truncatedNote: "工具参数/结果已截断",
    fullNote: "工具参数/结果完整保留",
  },
  en: {
    report: "Session Insights Report",
    generatedBy: "Generated by dsh-session-lens",
    privacyNote: "Privacy: this file contains no system prompt or internal request events; local paths are masked as ~; images are not exported.",
    privacyNoteFull: "Privacy: this file contains no system prompt or internal request events; images are not exported.",
    tokens: "Token usage",
    input: "Input",
    output: "Output",
    cacheRead: "Cache read",
    cacheWrite: "Cache write",
    reasoning: "Reasoning",
    compaction: "Compaction call",
    total: "Total",
    perTurn: "Per-turn breakdown",
    turn: "Turn",
    duration: "Duration",
    toolCalls: "Tool calls",
    errors: "Errors",
    messages: "Messages",
    tools: "Tool stats",
    tool: "Tool",
    calls: "Calls",
    activity: "Activity",
    compactions: "Compactions",
    shadowed: "Shadowed tokens",
    approvals: "Approvals",
    subagents: "Subagents",
    retries: "LLM retries",
    replay: "Replay",
    reasoningToggle: "Reasoning",
    toolArgs: "Arguments",
    toolResult: "Result",
    errorBadge: "error",
    turnDivider: "Turn",
    approvalAsked: "Approval requested",
    approvalApproved: "Approved",
    approvalDenied: "Denied",
    compactionMarker: "Context compaction",
    subagentMarker: "Subagent",
    planMode: "Plan mode",
    todoUpdated: "Todo update",
    feedback: "Feedback",
    user: "User",
    assistant: "Assistant",
    model: "Model",
    status: "Status",
    statusActive: "active",
    createdAt: "Created",
    eventCount: "Events",
    truncatedNote: "tool arguments/results truncated",
    fullNote: "tool arguments/results kept in full",
  },
} as const;

type Strings = Record<keyof (typeof STRINGS)["zh"], string>;

/** HTML-escape every dynamic string. */
export function esc(value: unknown): string {
  return String(value ?? "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

function fmtTime(ms: number | null, lang: Lang): string {
  if (ms === null) return "—";
  return new Intl.DateTimeFormat(lang === "zh" ? "zh-CN" : "en-US", {
    dateStyle: "medium",
    timeStyle: "medium",
  }).format(new Date(ms));
}

const TOKEN_SEGMENTS = [
  { key: "input", color: "#4c8dff" },
  { key: "output", color: "#34c98e" },
  { key: "cacheRead", color: "#8b7cf6" },
  { key: "cacheWrite", color: "#c9a0f6" },
  { key: "reasoning", color: "#f6a35c" },
] as const;

/** Stacked horizontal token bar as inline SVG (empty string when no usage). */
function tokenBarSvg(a: SessionAnalytics, s: Strings): string {
  const segments = TOKEN_SEGMENTS.map((seg) => ({
    label: s[seg.key],
    color: seg.color,
    value: a.tokens[seg.key],
  })).filter((seg) => seg.value > 0);
  const total = segments.reduce((sum, seg) => sum + seg.value, 0);
  if (total === 0) return "";
  const width = 720;
  const height = 22;
  let x = 0;
  const rects: string[] = [];
  for (const seg of segments) {
    const w = Math.max(2, Math.round((seg.value / total) * width));
    rects.push(`<rect x="${x}" y="0" width="${Math.min(w, width - x)}" height="${height}" fill="${seg.color}"><title>${esc(seg.label)} ${formatTokens(seg.value)}</title></rect>`);
    x += w;
    if (x >= width) break;
  }
  const legend = segments
    .map(
      (seg) =>
        `<span class="legend-item"><span class="legend-dot" style="background:${seg.color}"></span>${esc(seg.label)} ${formatTokens(seg.value)}</span>`,
    )
    .join("");
  return `<svg viewBox="0 0 ${width} ${height}" class="token-bar" role="img" aria-label="${esc(s.tokens)}">${rects.join("")}</svg><div class="legend">${legend}</div>`;
}

function statChip(label: string, value: string): string {
  return `<div class="chip"><div class="chip-value">${esc(value)}</div><div class="chip-label">${esc(label)}</div></div>`;
}

function renderStats(a: SessionAnalytics, s: Strings, lang: Lang): string {
  const turnRows = a.perTurn
    .map(
      (t) => `<tr>
<td>#${t.turn}</td>
<td>${esc(formatDuration(t.durationMs))}</td>
<td>${formatTokens(t.input + t.cacheRead + t.cacheWrite)}</td>
<td>${formatTokens(t.output)}</td>
<td>${t.reasoning > 0 ? formatTokens(t.reasoning) : "—"}</td>
<td>${t.toolCalls}${t.toolErrors > 0 ? ` <span class="err">(${t.toolErrors} ${esc(s.errors)})</span>` : ""}</td>
</tr>`,
    )
    .join("");

  const toolRows = a.tools
    .map((tool) => {
      const rate = tool.calls > 0 ? Math.round(((tool.calls - tool.errors) / tool.calls) * 100) : 100;
      return `<tr>
<td><code>${esc(tool.name)}</code></td>
<td>${tool.calls}</td>
<td>${tool.errors > 0 ? `<span class="err">${tool.errors}</span>` : "0"}</td>
<td>${rate}%</td>
<td>${esc(formatDuration(tool.totalDurationMs))}</td>
</tr>`;
    })
    .join("");

  const act = a.activity;
  const activityItems: Array<[string, string]> = [
    [s.compactions, String(act.compactions)],
    [s.shadowed, act.compactionShadowedTokens > 0 ? formatTokens(act.compactionShadowedTokens) : "—"],
    [s.approvals, `${act.approvalsApproved}/${act.approvalsAsked}`],
    [s.subagents, String(act.subagents)],
    [s.retries, String(act.llmRetries)],
  ];

  return `<section class="stats">
<h2>${esc(s.tokens)}</h2>
<div class="chips">
${statChip(s.total, formatTokens(a.tokens.total))}
${statChip(s.input, formatTokens(a.tokens.input))}
${statChip(s.output, formatTokens(a.tokens.output))}
${statChip(s.cacheRead, formatTokens(a.tokens.cacheRead))}
${statChip(s.cacheWrite, formatTokens(a.tokens.cacheWrite))}
${statChip(s.reasoning, formatTokens(a.tokens.reasoning))}
${a.compactionTokens !== null ? statChip(s.compaction, formatTokens(a.compactionTokens.total)) : ""}
</div>
${tokenBarSvg(a, s)}
${a.perTurn.length > 0 ? `<h2>${esc(s.perTurn)}</h2>
<table><thead><tr><th>${esc(s.turn)}</th><th>${esc(s.duration)}</th><th>${esc(s.input)}+${esc(s.cacheRead)}</th><th>${esc(s.output)}</th><th>${esc(s.reasoning)}</th><th>${esc(s.toolCalls)}</th></tr></thead>
<tbody>${turnRows}</tbody></table>` : ""}
${a.tools.length > 0 ? `<h2>${esc(s.tools)}</h2>
<table><thead><tr><th>${esc(s.tool)}</th><th>${esc(s.calls)}</th><th>${esc(s.errors)}</th><th>OK%</th><th>${esc(s.duration)}</th></tr></thead>
<tbody>${toolRows}</tbody></table>` : ""}
<h2>${esc(s.activity)}</h2>
<div class="activity">${activityItems.map(([k, v]) => `<span class="activity-item"><b>${esc(v)}</b> ${esc(k)}</span>`).join("")}</div>
</section>`;
}

function detailsBlock(summary: string, body: string, extraClass = ""): string {
  return `<details class="fold ${extraClass}"><summary>${esc(summary)}</summary><pre>${esc(body)}</pre></details>`;
}

function formatArgs(raw: string): string {
  try {
    return JSON.stringify(JSON.parse(raw), null, 2);
  } catch {
    return raw;
  }
}

function renderBlocks(blocks: ContentBlock[] | undefined, s: Strings, isAssistant: boolean): string {
  if (!Array.isArray(blocks)) return "";
  const parts: string[] = [];
  for (const block of blocks) {
    if (block.type === "reasoning" && typeof block.text === "string" && block.text.length > 0) {
      parts.push(detailsBlock(`${s.reasoningToggle} (${block.text.length} chars)`, block.text, "reasoning"));
    } else if (block.type === "text" && typeof block.text === "string" && block.text.length > 0) {
      parts.push(`<div class="msg-text">${esc(block.text)}</div>`);
    } else if (block.type === "tool-call") {
      const call = block as { name?: string; arguments?: string };
      parts.push(
        `<div class="tool-call"><span class="tool-badge">⚙ ${esc(call.name ?? "tool")}</span>${detailsBlock(
          s.toolArgs,
          formatArgs(typeof call.arguments === "string" ? call.arguments : ""),
        )}</div>`,
      );
    }
  }
  return parts.join("");
}

function renderReplay(events: SessionEvent[], s: Strings): string {
  const out: string[] = [];
  for (const event of events) {
    const data = asRecord(event.data);
    switch (event.type) {
      case "turn/start": {
        const turn = typeof data?.turn === "number" ? data.turn : "?";
        out.push(`<div class="turn-divider"><span>${esc(s.turnDivider)} ${turn}</span></div>`);
        break;
      }
      case "user/message": {
        const body = renderBlocks((data as unknown as { content?: ContentBlock[] })?.content, s, false);
        out.push(`<div class="msg user"><div class="msg-role">${esc(s.user)}</div>${body}</div>`);
        break;
      }
      case "assistant/message": {
        const provenance = assistantProvenance(event.data);
        const model = provenance?.model ? ` · ${esc(provenance.model)}` : "";
        out.push(`<div class="msg assistant"><div class="msg-role">${esc(s.assistant)}${model}</div>${renderBlocks(assistantContent(event.data), s, true)}</div>`);
        break;
      }
      case "tool/call": {
        const name = typeof data?.name === "string" ? data.name : "tool";
        const args = typeof data?.arguments === "string" ? data.arguments : "";
        out.push(`<div class="msg tool"><div class="msg-role">⚙ ${esc(name)}</div>${detailsBlock(s.toolArgs, formatArgs(args))}</div>`);
        break;
      }
      case "tool/result": {
        const isErr = toolResultIsError(event.data);
        const text = textOf(toolResultContent(event.data));
        out.push(
          `<div class="msg result${isErr ? " failed" : ""}"><div class="msg-role">${esc(s.toolResult)}${isErr ? ` <span class="err">(${esc(s.errorBadge)})</span>` : ""}</div>${detailsBlock(s.toolResult, text)}</div>`,
        );
        break;
      }
      case "approval/asked": {
        const tool = typeof data?.toolName === "string" ? data.toolName : "";
        out.push(`<div class="marker">🛡 ${esc(s.approvalAsked)}: <code>${esc(tool)}</code></div>`);
        break;
      }
      case "approval/decided": {
        const outcome = typeof data?.outcome === "string" ? data.outcome : "";
        const approved = outcome === "approved" || outcome === "allow" || outcome === "yes";
        out.push(`<div class="marker">${approved ? "✅" : "⛔"} ${approved ? esc(s.approvalApproved) : esc(s.approvalDenied)}</div>`);
        break;
      }
      case "compaction/summary": {
        const shadowed = typeof data?.shadowedTokenCount === "number" ? ` · ${formatTokens(data.shadowedTokenCount)} tokens` : "";
        out.push(`<div class="marker">🗜 ${esc(s.compactionMarker)}${shadowed}</div>`);
        break;
      }
      case "subagent/descriptor": {
        const role = typeof data?.role === "string" ? data.role : typeof data?.id === "string" ? data.id : "";
        out.push(`<div class="marker">🐳 ${esc(s.subagentMarker)}: ${esc(role)}</div>`);
        break;
      }
      case "plan/mode": {
        out.push(`<div class="marker">📋 ${esc(s.planMode)}</div>`);
        break;
      }
      case "todo/write": {
        out.push(`<div class="marker">☑ ${esc(s.todoUpdated)}</div>`);
        break;
      }
      case "feedback/record": {
        out.push(`<div class="marker">💬 ${esc(s.feedback)}</div>`);
        break;
      }
      default:
        break;
    }
  }
  return out.join("\n");
}

/** Light palette (base rules; shared by every theme). */
const LIGHT_CSS = `
*{box-sizing:border-box}
body{margin:0;padding:32px 16px;font-family:-apple-system,"Segoe UI","PingFang SC","Microsoft YaHei",system-ui,sans-serif;background:#f6f7f9;color:#1c1f24;line-height:1.65}
main{max-width:860px;margin:0 auto}
header.report{margin-bottom:24px}
h1{font-size:22px;margin:0 0 8px}
h2{font-size:15px;margin:22px 0 8px;color:#5a6472}
.meta{color:#5a6472;font-size:13px;display:flex;flex-wrap:wrap;gap:6px 14px}
.chips{display:flex;flex-wrap:wrap;gap:10px;margin:12px 0}
.chip{background:#fff;border:1px solid #e3e7ec;border-radius:10px;padding:8px 14px;min-width:96px}
.chip-value{font-size:17px;font-weight:650;font-variant-numeric:tabular-nums}
.chip-label{font-size:11px;color:#5a6472}
.token-bar{width:100%;border-radius:6px;overflow:hidden;display:block;background:#e9edf1}
.legend{display:flex;flex-wrap:wrap;gap:4px 14px;margin-top:6px;font-size:12px;color:#5a6472}
.legend-dot{display:inline-block;width:9px;height:9px;border-radius:3px;margin-right:5px}
table{width:100%;border-collapse:collapse;background:#fff;border:1px solid #e3e7ec;border-radius:10px;overflow:hidden;font-size:13px}
th,td{text-align:left;padding:7px 12px;border-bottom:1px solid #eef1f4;font-variant-numeric:tabular-nums}
th{background:#f0f2f5;font-weight:600;color:#455060;font-size:12px}
tr:last-child td{border-bottom:none}
code{background:#eef1f4;border-radius:5px;padding:1px 6px;font-size:12px}
.err{color:#d6453d}
.activity{display:flex;flex-wrap:wrap;gap:8px 18px;font-size:13px;color:#455060}
.msg{margin:10px 0;padding:12px 16px;border-radius:12px;background:#fff;border:1px solid #e3e7ec}
.msg.user{background:#eef4ff;border-color:#d5e3fb}
.msg.tool,.msg.result{background:#fafbfc}
.msg.failed{border-color:#f0c8c5}
.msg-role{font-size:12px;font-weight:650;color:#5a6472;margin-bottom:6px;text-transform:uppercase;letter-spacing:.04em}
.msg-text{white-space:pre-wrap;word-break:break-word;font-size:14px}
.fold{margin:6px 0}
.fold summary{cursor:pointer;font-size:12px;color:#4c8dff;user-select:none}
.fold pre{margin:8px 0 2px;padding:10px 12px;background:#f0f2f5;border-radius:8px;font-size:12px;white-space:pre-wrap;word-break:break-all;max-height:420px;overflow:auto}
.fold.reasoning pre{color:#5a6472;font-style:italic}
.tool-badge{display:inline-block;background:#e8eeff;color:#3a63c8;border-radius:6px;padding:2px 8px;font-size:12px;margin-bottom:4px}
.turn-divider{display:flex;align-items:center;gap:12px;margin:22px 0 6px;color:#8a94a1;font-size:12px;font-weight:650;letter-spacing:.08em;text-transform:uppercase}
.turn-divider::before,.turn-divider::after{content:"";flex:1;border-top:1px solid #dfe4ea}
.marker{margin:6px 0;padding:6px 12px;font-size:12px;color:#5a6472;background:#f0f2f5;border-radius:8px;display:inline-block}
footer{margin-top:28px;padding-top:14px;border-top:1px solid #e3e7ec;font-size:12px;color:#8a94a1}
footer a{color:#4c8dff;text-decoration:none}
.privacy{margin-top:6px}
`;

/** Dark palette: overrides on top of LIGHT_CSS (same values as the former
 *  `prefers-color-scheme: dark` block, so "dark" renders identically). */
const DARK_CSS = `
body{background:#14161a;color:#dde2e8}
.chip,table,.msg{background:#1c1f24;border-color:#2c313a}
th{background:#22262d;color:#a7b0bc}
td{border-color:#262b33}
code{background:#262b33}
.msg.user{background:#17233a;border-color:#24365c}
.msg.tool,.msg.result{background:#191c21}
.msg.failed{border-color:#5c2f2c}
.fold pre{background:#22262d}
.marker{background:#22262d;color:#a7b0bc}
.turn-divider::before,.turn-divider::after{border-color:#2c313a}
footer{border-color:#2c313a}
.token-bar{background:#262b33}
h2,.meta,.chip-label,.msg-role,.activity{color:#8a94a1}
`;

function buildCss(theme: ExportTheme): string {
  const root =
    theme === "dark"
      ? ":root{color-scheme:dark}"
      : theme === "light"
        ? ":root{color-scheme:light}"
        : ":root{color-scheme:light dark}";
  if (theme === "light") return `${root}\n${LIGHT_CSS}`;
  if (theme === "dark") return `${root}\n${LIGHT_CSS}\n${DARK_CSS}`;
  return `${root}\n${LIGHT_CSS}\n@media (prefers-color-scheme:dark){\n${DARK_CSS}\n}`;
}

/**
 * Render the full export document. `events` should be the session's expanded
 * event stream (unfiltered — story filtering and redaction happen here).
 */
export function renderSessionHtml(
  events: SessionEvent[],
  analyticsInput?: SessionAnalytics,
  header?: SessionHeader | null,
  options: ExportOptions = {},
): string {
  const lang: Lang = options.lang === "en" ? "en" : "zh";
  const theme: ExportTheme = options.theme ?? "dark";
  const s: Strings = STRINGS[lang];
  const analytics = analyticsInput ?? analyzeSession(events, header);
  const story = redactEvents(filterStoryEvents(events), options);

  const title = analytics.title ?? analytics.sessionId ?? "session";
  const modelLabel = analytics.models.join(", ") || "—";
  const truncated = (options.maxTextLength === undefined ? 2000 : options.maxTextLength) !== null;
  const masked = options.maskPaths !== false;
  const statusLabel = analytics.status === "active" ? s.statusActive : analytics.status;

  return `<!doctype html>
<html lang="${lang === "zh" ? "zh-CN" : "en"}">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'; img-src data:;">
<title>${esc(title)} · ${esc(s.report)}</title>
<style>${buildCss(theme)}</style>
</head>
<body>
<main>
<header class="report">
<h1>${esc(title)}</h1>
<div class="meta">
<span>${esc(s.model)}: ${esc(modelLabel)}</span>
<span>${esc(s.status)}: ${esc(statusLabel)}</span>
<span>${esc(s.createdAt)}: ${esc(fmtTime(analytics.createdAt ?? analytics.firstEventAt, lang))}</span>
<span>${esc(s.duration)}: ${esc(formatDuration(analytics.durationMs))}</span>
<span>${esc(s.turn)}: ${analytics.turns}</span>
<span>${esc(s.messages)}: ${analytics.userMessages + analytics.assistantMessages}</span>
<span>${esc(s.eventCount)}: ${analytics.eventCount}</span>
</div>
</header>
${renderStats(analytics, s, lang)}
<h2>${esc(s.replay)}</h2>
<section class="replay">
${renderReplay(story, s)}
</section>
<footer>
<div>${esc(s.generatedBy)} · <a href="https://github.com/bobostudio/dsh-session-lens">github.com/bobostudio/dsh-session-lens</a> · ${esc(truncated ? s.truncatedNote : s.fullNote)}</div>
<div class="privacy">${esc(masked ? s.privacyNote : s.privacyNoteFull)}</div>
</footer>
</main>
</body>
</html>
`;
}
